[package]
name = "winoxide-exec"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Windows PE execution engine — loads, resolves imports, and runs executables"

[features]
default = ["native"]
native = ["winoxide-kernel32", "winoxide-msvcrt", "winoxide-registry"]

[dependencies]
winoxide-types = { path = "../winoxide-types" }
winoxide-pe = { path = "../winoxide-pe" }
serde = { version = "1", features = ["derive"] }
winoxide-kernel32 = { path = "../winoxide-kernel32", optional = true }
winoxide-msvcrt = { path = "../winoxide-msvcrt", optional = true }
winoxide-registry = { path = "../winoxide-registry", optional = true }
